"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { SiteHeader } from "@/components/SiteHeader";
import { BrainMap } from "@/components/BrainMap";
import { RichMarkdown, type AllowedLink } from "@/components/Rich";
import { detectLang, strings, type Lang } from "@/lib/i18n";
import type { IndexedNote } from "@/lib/types";
import { displayTitle, humanizeSlug } from "@/lib/noteTitle";

/**
 * Second Self (browse view) — the SAME public notes the chat agent is
 * grounded in, browsable directly: a sidenav of folders on the left, the
 * selected note's content on the right (or the brain graph, ported from
 * ohmyself!'s own dashboard, as an alternate view). Nothing here is
 * generated by a model; it's Juan Diego's own public notes, verbatim.
 */

interface NoteSummary {
  path: string;
  title: string;
  type: string;
  tags: string[];
  links: string[];
  created?: string;
  updated?: string;
  excerpt?: string;
}

interface FolderEntry {
  key: string;
  label: string;
  items: NoteSummary[];
}

interface NoteFull {
  path: string;
  title: string;
  type: string;
  tags: string[];
  body: string;
  created?: string;
  updated?: string;
}

type ViewMode = "list" | "graph";

/** A note's OWN links — the only URLs that could ever legitimately appear
 *  while rendering it, so they double as its allowlist for RichMarkdown
 *  (no model in the loop here, unlike the chat). */
function extractUrls(body: string): string[] {
  const out = new Set<string>();
  const re = /https?:\/\/[^\s)\]}"'<>]+/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(body))) out.add(m[0].replace(/[.,;:!?]+$/, ""));
  return [...out];
}

/** Prefer the owner's bio as the default landing note — it's the most
 *  natural "front page" of this view. Falls back to the first note. */
function pickDefaultNote(notes: NoteSummary[]): NoteSummary | null {
  if (notes.length === 0) return null;
  return (
    notes.find((n) => n.path === "identity/bio.md") ??
    notes.find((n) => n.type === "identity" && n.title.toLowerCase() === "bio") ??
    notes[0]
  );
}

export default function BrainPage() {
  const [lang, setLang] = useState<Lang>("en");
  const [langReady, setLangReady] = useState(false);
  const [notes, setNotes] = useState<NoteSummary[] | null>(null);
  const [loadError, setLoadError] = useState(false);
  const [view, setView] = useState<ViewMode>("list");
  const [query, setQuery] = useState("");
  const [selectedPath, setSelectedPath] = useState<string | null>(null);
  const [selectedNote, setSelectedNote] = useState<NoteFull | null>(null);
  const [selectedLoading, setSelectedLoading] = useState(false);
  const [selectedError, setSelectedError] = useState(false);
  const [mobileNavOpen, setMobileNavOpen] = useState(false);

  const t = strings(lang);

  useEffect(() => {
    let chosen: Lang;
    try {
      const saved = localStorage.getItem("jds.lang");
      chosen = saved === "es" || saved === "en" ? saved : detectLang();
    } catch {
      chosen = detectLang();
    }
    setLang(chosen);
    if (typeof document !== "undefined") document.documentElement.lang = chosen;
    setLangReady(true);
  }, []);

  // Notes are written verbatim in whatever language JD wrote them in — the
  // list (titles/excerpts) is translated server-side to match the visitor's
  // language (cached — see lib/translate.ts), so this refetches whenever
  // `lang` changes, not just once on mount. Waits for `langReady` so it
  // never fires once with the wrong default language first.
  useEffect(() => {
    if (!langReady) return;
    let alive = true;
    fetch(`/api/brain/notes?lang=${lang}`)
      .then((r) => r.json())
      .then((d: { notes?: NoteSummary[] }) => {
        if (alive) setNotes(d.notes ?? []);
      })
      .catch(() => {
        if (alive) setLoadError(true);
      });
    return () => {
      alive = false;
    };
  }, [lang, langReady]);

  function onLang(next: Lang) {
    setLang(next);
    if (typeof document !== "undefined") document.documentElement.lang = next;
    try {
      localStorage.setItem("jds.lang", next);
    } catch {
      /* storage unavailable — fine, just won't persist */
    }
  }

  // Depends on `lang` so it always fetches the note translated into
  // whichever language is current — including re-fetching the ALREADY
  // OPEN note when the visitor flips languages (see the effect below).
  const selectNote = useCallback(
    (path: string) => {
      setSelectedPath(path);
      setSelectedNote(null);
      setSelectedError(false);
      setSelectedLoading(true);
      setMobileNavOpen(false);
      fetch(`/api/brain/note?path=${encodeURIComponent(path)}&lang=${lang}`)
        .then((r) => r.json())
        .then((d: { note?: NoteFull }) => {
          if (d.note) setSelectedNote(d.note);
          else setSelectedError(true);
        })
        .catch(() => setSelectedError(true))
        .finally(() => setSelectedLoading(false));
    },
    [lang],
  );

  // Land on the bio by default, once notes are in — this view should open
  // on "who is this", not an empty pane.
  useEffect(() => {
    if (!notes || selectedPath) return;
    const def = pickDefaultNote(notes);
    if (def) selectNote(def.path);
  }, [notes, selectedPath, selectNote]);

  // Re-translate the note currently open whenever the visitor switches
  // language — without this, only NEW selections would pick up the right
  // language and an already-open note would silently stay in the old one.
  useEffect(() => {
    if (!langReady || !selectedPath) return;
    selectNote(selectedPath);
    // Only `lang` (via selectNote's closure) should re-trigger this — not
    // every time selectNote is recreated for unrelated reasons.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [lang]);

  const filtered = useMemo(() => {
    if (!notes) return [];
    const q = query.trim().toLowerCase();
    if (!q) return notes;
    return notes.filter(
      (n) => n.title.toLowerCase().includes(q) || n.tags.some((tg) => tg.toLowerCase().includes(q)),
    );
  }, [notes, query]);

  // Group by real folder structure, not the raw `type` field — a note under
  // `projects/<slug>/...` (an overview, a note, a spec, a subproject) is
  // part of THAT project's folder, never its own top-level bucket. Without
  // this, e.g. ohmyself's spec docs would show as a random "spec" folder
  // sitting next to "identity" instead of nested under "ohmyself". Projects
  // themselves nest one level deeper, under a single "Projects" group,
  // instead of sitting as flat top-level folders next to identity/books/etc.
  const { topEntries, projectEntries } = useMemo(() => {
    const top = new Map<string, NoteSummary[]>();
    const projects = new Map<string, NoteSummary[]>();
    for (const n of filtered) {
      const [first, second] = n.path.split("/");
      if (first === "projects" && second) {
        const arr = projects.get(second) ?? [];
        arr.push(n);
        projects.set(second, arr);
      } else {
        const key = first || n.type;
        const arr = top.get(key) ?? [];
        arr.push(n);
        top.set(key, arr);
      }
    }
    const top_: FolderEntry[] = [];
    for (const [key, items] of top) {
      items.sort((a, b) => a.title.localeCompare(b.title));
      top_.push({ key, label: key, items });
    }
    // "identity" leads — it's the natural front door of this view
    // (who this even is), everything else follows alphabetically.
    top_.sort((a, b) => {
      if (a.key === "identity") return -1;
      if (b.key === "identity") return 1;
      return a.label.localeCompare(b.label);
    });
    const projects_: FolderEntry[] = [];
    for (const [slug, items] of projects) {
      items.sort((a, b) => a.title.localeCompare(b.title));
      const overview = items.find((n) => n.path === `projects/${slug}/_index.md`);
      projects_.push({ key: slug, label: overview?.title || humanizeSlug(slug), items });
    }
    projects_.sort((a, b) => a.label.localeCompare(b.label));
    return { topEntries: top_, projectEntries: projects_ };
  }, [filtered]);

  const graphNotes: IndexedNote[] = useMemo(
    () =>
      (notes ?? []).map((n) => ({
        path: n.path,
        title: displayTitle(n.title, n.path),
        type: n.type,
        visibility: "public" as const,
        tags: n.tags,
        links: n.links,
        created: n.created,
        updated: n.updated,
        excerpt: n.excerpt,
      })),
    [notes],
  );

  const loadSemantic = useCallback(async () => {
    const res = await fetch("/api/brain/semantic");
    const data = (await res.json()) as {
      enabled?: boolean;
      edges?: { a: string; b: string; score: number }[];
    };
    return { enabled: Boolean(data.enabled), edges: data.edges ?? [] };
  }, []);

  const noteLinks: AllowedLink[] = useMemo(
    () => (selectedNote ? extractUrls(selectedNote.body).map((url) => ({ url, label: selectedNote.title })) : []),
    [selectedNote],
  );

  const openFromGraph = useCallback(
    (path: string) => {
      setView("list");
      selectNote(path);
    },
    [selectNote],
  );

  const sidenav = (
    <>
      <input
        value={query}
        onChange={(e) => setQuery(e.target.value)}
        placeholder={t.brain.searchPlaceholder}
        className="mb-3 w-full shrink-0 rounded-xl border border-border bg-bg px-3.5 py-2 text-sm text-ink placeholder:text-faint focus:border-brand focus:outline-none"
        aria-label={t.brain.searchPlaceholder}
      />
      <div className="-mr-2 flex-1 overflow-y-auto pr-2" style={{ scrollbarGutter: "stable" }}>
        {!notes && !loadError && <p className="px-1 text-sm text-muted">{t.brain.loading}</p>}
        {loadError && <p className="px-1 text-sm text-muted">{t.brain.loadError}</p>}
        {notes && notes.length === 0 && (
          <div className="rounded-2xl border border-dashed border-border p-6 text-center">
            <p className="font-heading text-sm font-semibold">{t.brain.emptyTitle}</p>
            <p className="mt-1 text-xs text-muted">{t.brain.emptySub}</p>
          </div>
        )}
        <div className="space-y-2 pb-2">
          {topEntries.map((g) => (
            <FolderGroup
              key={g.key}
              label={g.label}
              items={g.items}
              activePath={selectedPath}
              onOpen={selectNote}
              defaultOpen={g.key === "identity"}
            />
          ))}
          {projectEntries.length > 0 && (
            <ProjectsGroup label={t.brain.projectsLabel} projects={projectEntries} activePath={selectedPath} onOpen={selectNote} />
          )}
        </div>
      </div>
    </>
  );

  return (
    <main className="mx-auto flex h-[100dvh] w-full max-w-6xl flex-col px-5 sm:px-8">
      <SiteHeader lang={lang} onLang={onLang} active="brain" />

      <div className="flex flex-wrap items-center justify-between gap-3 pb-4">
        <div>
          <h2 className="font-heading text-lg font-semibold tracking-tight">{t.brain.title}</h2>
          <p className="text-sm text-muted">{t.brain.subtitle}</p>
        </div>
        <div className="flex items-center gap-2">
          {notes && <span className="hidden text-xs text-faint sm:inline">{t.brain.notesCount(notes.length)}</span>}
          <button
            type="button"
            onClick={() => setMobileNavOpen(true)}
            className="rounded-full border border-border bg-surface px-3 py-1.5 text-xs font-medium text-muted transition-colors hover:text-ink sm:hidden"
          >
            {t.brain.listView}
          </button>
          <div className="flex items-center rounded-full border border-border bg-surface p-0.5 text-xs">
            <button
              type="button"
              onClick={() => setView("list")}
              className={`rounded-full px-3 py-1.5 font-medium transition-colors ${
                view === "list" ? "bg-brand text-white" : "text-muted hover:text-ink"
              }`}
            >
              {t.brain.listView}
            </button>
            <button
              type="button"
              onClick={() => setView("graph")}
              className={`flex items-center gap-1.5 rounded-full px-3 py-1.5 font-medium transition-colors ${
                view === "graph" ? "bg-brand text-white" : "text-muted hover:text-ink"
              }`}
            >
              <BrainGlowIcon />
              {t.brain.graphView}
            </button>
          </div>
        </div>
      </div>

      {view === "list" ? (
        <div className="flex flex-1 gap-4 overflow-hidden pb-4">
          <aside className="hidden w-64 shrink-0 flex-col overflow-hidden rounded-2xl border border-border bg-surface p-3 sm:flex">
            {sidenav}
          </aside>
          <section className="flex-1 overflow-y-auto rounded-2xl border border-border bg-surface px-5 py-5 sm:px-8 sm:py-6" style={{ scrollbarGutter: "stable" }}>
            {selectedLoading && <p className="text-sm text-muted">{t.brain.loading}</p>}
            {!selectedLoading && selectedError && <p className="text-sm text-muted">{t.brain.loadError}</p>}
            {!selectedLoading && !selectedError && selectedNote && (
              <>
                <div className="mb-4 border-b border-border pb-4">
                  <p className="font-heading text-xl font-semibold tracking-tight text-ink">
                    {displayTitle(selectedNote.title, selectedNote.path)}
                  </p>
                  <p className="mt-1 text-xs capitalize text-faint">
                    {selectedNote.type}
                    {selectedNote.updated ? ` · ${selectedNote.updated}` : ""}
                  </p>
                </div>
                <div className="prose">
                  <RichMarkdown lang={lang} allowedLinks={noteLinks}>
                    {selectedNote.body}
                  </RichMarkdown>
                </div>
              </>
            )}
            {!selectedLoading && !selectedError && !selectedNote && notes && notes.length === 0 && (
              <div className="rounded-2xl border border-dashed border-border p-8 text-center">
                <p className="font-heading text-base font-semibold">{t.brain.emptyTitle}</p>
                <p className="mt-1 text-sm text-muted">{t.brain.emptySub}</p>
              </div>
            )}
          </section>
        </div>
      ) : (
        <div className="relative mb-4 flex-1 overflow-hidden rounded-2xl border border-border">
          <BrainMap notes={graphNotes} onOpenNote={openFromGraph} loadSemantic={loadSemantic} />
        </div>
      )}

      {mobileNavOpen && (
        <div
          className="fixed inset-0 z-40 flex bg-black/50 backdrop-blur-sm sm:hidden"
          onClick={() => setMobileNavOpen(false)}
          role="dialog"
          aria-modal="true"
        >
          <div
            className="flex h-full w-full max-w-xs flex-col border-r border-border bg-bg p-3 shadow-2xl"
            onClick={(e) => e.stopPropagation()}
          >
            <div className="mb-2 flex items-center justify-between">
              <span className="font-heading text-sm font-semibold text-ink">{t.brain.title}</span>
              <button
                type="button"
                onClick={() => setMobileNavOpen(false)}
                aria-label={t.brain.close}
                className="grid h-8 w-8 place-items-center rounded-full text-muted transition-colors hover:bg-surface hover:text-ink"
              >
                <CloseIcon />
              </button>
            </div>
            {sidenav}
          </div>
        </div>
      )}
    </main>
  );
}

function FolderGroup({
  label,
  items,
  activePath,
  onOpen,
  nested = false,
  defaultOpen = false,
}: {
  label: string;
  items: NoteSummary[];
  activePath: string | null;
  onOpen: (path: string) => void;
  nested?: boolean;
  defaultOpen?: boolean;
}) {
  const [open, setOpen] = useState(defaultOpen);
  return (
    <div className="overflow-hidden rounded-xl">
      <button
        type="button"
        onClick={() => setOpen((o) => !o)}
        className="flex w-full items-center justify-between gap-2 px-2 py-1.5 text-left transition-colors hover:bg-elevated rounded-lg"
        aria-expanded={open}
      >
        <span
          className={`flex items-center gap-2 font-heading uppercase tracking-wide text-muted ${
            nested ? "text-[11px] font-medium" : "text-xs font-semibold"
          }`}
        >
          <FolderIcon open={open} />
          {label}
        </span>
        <span className="text-xs text-faint">{items.length}</span>
      </button>
      {open && (
        <ul className="mt-0.5 space-y-0.5">
          {items.map((n) => (
            <li key={n.path}>
              <button
                type="button"
                onClick={() => onOpen(n.path)}
                aria-current={activePath === n.path ? "page" : undefined}
                className={`flex w-full items-center gap-2 rounded-lg px-2.5 py-1.5 text-left text-sm transition-colors ${
                  activePath === n.path ? "bg-brand text-white" : "text-ink hover:bg-elevated"
                }`}
              >
                <span className="min-w-0 flex-1 truncate">{displayTitle(n.title, n.path)}</span>
              </button>
            </li>
          ))}
        </ul>
      )}
    </div>
  );
}

/** A single top-level "Projects" folder whose children are each project's
 *  own sub-folder — mirrors the real `projects/<slug>/...` structure instead
 *  of flattening every project into a top-level bucket next to identity. */
function ProjectsGroup({
  label,
  projects,
  activePath,
  onOpen,
}: {
  label: string;
  projects: FolderEntry[];
  activePath: string | null;
  onOpen: (path: string) => void;
}) {
  const [open, setOpen] = useState(false);
  const total = projects.reduce((sum, p) => sum + p.items.length, 0);
  return (
    <div className="overflow-hidden rounded-xl">
      <button
        type="button"
        onClick={() => setOpen((o) => !o)}
        className="flex w-full items-center justify-between gap-2 px-2 py-1.5 text-left transition-colors hover:bg-elevated rounded-lg"
        aria-expanded={open}
      >
        <span className="flex items-center gap-2 font-heading text-xs font-semibold uppercase tracking-wide text-muted">
          <FolderIcon open={open} />
          {label}
        </span>
        <span className="text-xs text-faint">{total}</span>
      </button>
      {open && (
        <div className="ml-2.5 mt-0.5 space-y-0.5 border-l border-border pl-2">
          {projects.map((p) => (
            <FolderGroup key={p.key} label={p.label} items={p.items} activePath={activePath} onOpen={onOpen} nested />
          ))}
        </div>
      )}
    </div>
  );
}

function FolderIcon({ open }: { open: boolean }) {
  return open ? (
    <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="shrink-0" aria-hidden>
      <path d="M3 7a2 2 0 0 1 2-2h4l2 2h8a2 2 0 0 1 2 2v1H3V7Z" />
      <path d="M3 10h18l-1.5 9.5A2 2 0 0 1 17.53 21H6.47a2 2 0 0 1-1.97-1.5L3 10Z" />
    </svg>
  ) : (
    <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="shrink-0" aria-hidden>
      <path d="M3 7a2 2 0 0 1 2-2h4l2 2h8a2 2 0 0 1 2 2v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V7Z" />
    </svg>
  );
}

function CloseIcon() {
  return (
    <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.25" strokeLinecap="round" strokeLinejoin="round" aria-hidden>
      <path d="M18 6 6 18" />
      <path d="M6 6l12 12" />
    </svg>
  );
}

/** A tiny node-cluster glyph whose colors continuously cycle — a playful,
 *  literal preview of the graph view it sits next to. */
function BrainGlowIcon() {
  return (
    <svg width="15" height="15" viewBox="0 0 24 24" fill="none" className="brain-glow-icon shrink-0" aria-hidden>
      <g stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" opacity="0.5">
        <path d="M12 5 6.5 9.5" />
        <path d="M12 5 17.5 9.5" />
        <path d="M6.5 9.5 6.5 14.5" />
        <path d="M17.5 9.5 17.5 14.5" />
        <path d="M6.5 14.5 12 19" />
        <path d="M17.5 14.5 12 19" />
        <path d="M6.5 9.5 17.5 14.5" />
      </g>
      <circle cx="12" cy="5" r="2.1" fill="oklch(0.78 0.17 145)" className="brain-glow-dot" style={{ animationDelay: "0s" }} />
      <circle cx="6.5" cy="9.5" r="2.1" fill="oklch(0.75 0.14 195)" className="brain-glow-dot" style={{ animationDelay: "0.3s" }} />
      <circle cx="17.5" cy="9.5" r="2.1" fill="oklch(0.78 0.19 350)" className="brain-glow-dot" style={{ animationDelay: "0.6s" }} />
      <circle cx="6.5" cy="14.5" r="2.1" fill="oklch(0.8 0.17 90)" className="brain-glow-dot" style={{ animationDelay: "0.9s" }} />
      <circle cx="17.5" cy="14.5" r="2.1" fill="oklch(0.76 0.16 280)" className="brain-glow-dot" style={{ animationDelay: "1.2s" }} />
      <circle cx="12" cy="19" r="2.1" fill="oklch(0.84 0.15 135)" className="brain-glow-dot" style={{ animationDelay: "1.5s" }} />
    </svg>
  );
}
