/**
 * Machine-provisioned personal brains (bonds ai-in-chat, adenda 8 / W-S1).
 *
 * A `self` space provisioned by a service account is one person's private
 * brain — identity, people, projects, goals, decisions, journal — with no
 * ohmyself account behind it: bonds keys it by the person's mxid and talks to
 * it with `X-Brain-Space`. The taxonomy is the personal one (`DEFAULT_CONFIG`),
 * seeded at provisioning; this module adds the fixed notes a fresh personal
 * cocina starts with, the same way `scaffoldRelationshipCocina` does for a
 * room brain. Idempotent: provisioning re-fires on lifecycle events.
 */

import type { Brain } from "./brain.js";
import { NotFoundError } from "./errors.js";
import { KEEPER_ATTRIBUTION } from "./relationship.js";
import type { UserConfig } from "./config.js";
import type { Visibility } from "./types.js";

const ALL_VISIBILITIES: Visibility[] = ["public", "private", "secret"];

export interface PersonalScaffoldInput {
  /** Display name of the person (the space's name). */
  name: string;
}

/** The notes a machine-provisioned personal brain starts with. */
export const PERSONAL_SCAFFOLD_PATHS = ["_index.md", "identity/about-me.md"] as const;

/**
 * Create the personal cocina's fixed notes if missing:
 *  - `_index.md` — the postal, regenerated by the keeper after each journal pass;
 *  - `identity/about-me.md` — the identity page `who_am_i` aggregates and
 *    `update_identity` maintains. Created EMPTY on purpose: an empty page makes
 *    `who_am_i` say "identity pages exist but are empty" and invite the person
 *    to fill them in, whereas placeholder text would be read back as if it
 *    were who they are.
 * The remaining pillars (people/, projects/, goals/, journal/, memory/) are
 * folders of the taxonomy and come into being with their first note.
 */
export async function scaffoldPersonalCocina(
  brain: Brain,
  spaceId: string,
  config: UserConfig,
  input: PersonalScaffoldInput,
): Promise<{ created: string[] }> {
  const created: string[] = [];
  const name = input.name.trim() || "me";
  const stubs: { path: string; type: string; title: string; body: string; visibility: Visibility }[] = [
    {
      path: "_index.md",
      type: "note",
      title: name,
      visibility: "secret",
      body: [
        `Postal of ${name}'s brain. The keeper regenerates this note after each`,
        "journal pass: what is going on with this person right now and where to",
        "look next.",
        "",
        "_No journal has been distilled yet._",
      ].join("\n"),
    },
    {
      path: "identity/about-me.md",
      type: "identity",
      title: "About me",
      visibility: "private",
      body: "",
    },
  ];
  for (const stub of stubs) {
    const exists = await brain
      .readNote(spaceId, stub.path, ALL_VISIBILITIES)
      .then(() => true)
      .catch((err) => {
        if (err instanceof NotFoundError) return false;
        throw err;
      });
    if (exists) continue;
    await brain.createNote(
      spaceId,
      { type: stub.type, title: stub.title, body: stub.body, path: stub.path, visibility: stub.visibility },
      config,
      ALL_VISIBILITIES,
      KEEPER_ATTRIBUTION,
    );
    created.push(stub.path);
  }
  return { created };
}
