import fs from "node:fs/promises";
import path from "node:path";
import {
  argFor,
  defaultMcpUrl,
  ensureDir,
  hasFlag,
  mergeJsonFile,
  pathExists,
  slugify,
  writeFileIfAllowed,
} from "./util.js";
import { claudeDesktopConfig, cursorMcpConfig, type BrainMode, type InitClient } from "./mcp-snippets.js";

export interface InitOptions {
  cwd: string;
  name: string;
  slug: string;
  mode: BrainMode;
  mcpUrl: string;
  token?: string;
  spaceId?: string;
  scope: string;
  vaultDir: string;
  clients: InitClient[];
  force: boolean;
  ohmyselfRoot?: string;
}

function parseClients(raw?: string): InitClient[] {
  if (!raw) return ["cursor", "claude"];
  const allowed = new Set<InitClient>(["cursor", "claude", "codex"]);
  const picked = raw
    .split(",")
    .map((s) => s.trim().toLowerCase())
    .filter((s): s is InitClient => allowed.has(s as InitClient));
  return picked.length ? picked : ["cursor", "claude"];
}

async function findOhmyselfRoot(start: string): Promise<string | undefined> {
  let dir = start;
  for (let i = 0; i < 8; i++) {
    const pkgPath = path.join(dir, "server", "package.json");
    try {
      const raw = await fs.readFile(pkgPath, "utf8");
      const pkg = JSON.parse(raw) as { name?: string };
      if (pkg.name === "@ohmyself/server") return dir;
    } catch {
      /* keep walking */
    }
    const parent = path.dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }
  return undefined;
}

function buildConfigYaml(opts: InitOptions): string {
  const lines = [
    "# ohmyself project wiring — generated by `oms init`",
    "version: 1",
    "",
    "project:",
    `  name: ${yamlQuote(opts.name)}`,
    `  slug: ${yamlQuote(opts.slug)}`,
    "",
    "brain:",
    `  mode: ${opts.mode}`,
    `  default_scope: ${opts.scope}`,
  ];
  if (opts.spaceId) lines.push(`  space_id: ${yamlQuote(opts.spaceId)}`);
  if (opts.mode === "local") lines.push(`  vault_dir: ${yamlQuote(opts.vaultDir)}`);
  if (opts.ohmyselfRoot) lines.push(`  ohmyself_root: ${yamlQuote(opts.ohmyselfRoot)}`);

  lines.push(
    "",
    "mcp:",
    `  url: ${yamlQuote(opts.mcpUrl)}`,
    "  token_env: OMS_TOKEN",
    "",
    "skills:",
    "  # Canonical skills live in your brain (skills/<slug>/SKILL.md).",
    "  # Sync local copies with the sync-skills skill or MCP get_skill/save_skill.",
    "  recommended:",
    "    - task-operation-flowya",
    "    - ohmyself-space-routing",
    "    - wiki-governance",
    "",
    "clients:",
    ...opts.clients.map((c) => `  - ${c}`),
    "",
  );
  return lines.join("\n");
}

function yamlQuote(value: string): string {
  if (/^[a-zA-Z0-9_./:-]+$/.test(value)) return value;
  return JSON.stringify(value);
}

function buildReadme(opts: InitOptions): string {
  const tokenStep =
    opts.mode === "hosted"
      ? `1. Create a personal token at [www.ohmyself.ai](https://www.ohmyself.ai) → Settings → MCP → **Create token** (scope: \`${opts.scope}\`).
2. Copy it into \`.oms/secrets.env\`:
   \`\`\`
   OMS_TOKEN=oms_…
   \`\`\`
3. Re-run \`oms init --token "$OMS_TOKEN"\` or paste the token into \`.cursor/mcp.json\` / Claude config.`
      : `1. Put markdown notes in \`${opts.vaultDir}/\` (Obsidian-friendly).
2. Ensure the ohmyself server is available (monorepo: \`pnpm --filter @ohmyself/server mcp\`).
3. Open this folder in Cursor — MCP uses local stdio against the vault.`;

  return `# ohmyself — ${opts.name}

This folder is wired to your second brain via **ohmyself MCP**.

## Quick start

${tokenStep}

## Files

| Path | Purpose |
|------|---------|
| \`.oms/config.yml\` | Project ↔ brain binding (safe to commit) |
| \`.oms/secrets.env\` | \`OMS_TOKEN\` — **gitignored** |
| \`.oms/mcp/\` | Copy-paste snippets for other clients |
| \`.cursor/mcp.json\` | Cursor MCP (project-level) |

## Agent rules

- **Memory** → ohmyself (\`remember\`, \`write_brain\`, \`recall\`, …)
- **Tasks** → Flowya (\`create_task\`, never \`add_todo\`)
- **Company wiki** → \`list_spaces\` + \`*_space\` tools

Load \`task-operation-flowya\` at session start. For company spaces, load \`ohmyself-space-routing\`.

## Verify

In Cursor: reload window → MCP ohmyself green → run \`get_structure\`.

MCP contract: **2.7** · URL: \`${opts.mcpUrl}\`
`;
}

function codexTomlFragment(opts: InitOptions): string {
  const token = opts.token ?? "${OMS_TOKEN}";
  if (opts.mode === "local") {
    const vault = opts.vaultDir;
    return `# Merge into ~/.codex/config.toml [mcp_servers.ohmyself]
[mcp_servers.ohmyself]
command = "pnpm"
args = ["--filter", "@ohmyself/server", "mcp"]

[mcp_servers.ohmyself.env]
VAULT_BACKEND = "fs"
FS_VAULT_DIR = "${vault}"
OHMYSELF_USER_ID = "local"
OHMYSELF_SCOPE = "${opts.scope}"
`;
  }
  return `# Merge into ~/.codex/config.toml [mcp_servers.ohmyself]
[mcp_servers.ohmyself]
url = "${opts.mcpUrl}"

[mcp_servers.ohmyself.headers]
Authorization = "Bearer ${token}"
`;
}

export async function runInit(cwd: string): Promise<void> {
  const force = hasFlag("--force");
  const mode = (argFor("--mode") === "local" ? "local" : "hosted") as BrainMode;
  const name = argFor("--name") ?? path.basename(cwd);
  const slug = slugify(argFor("--slug") ?? name);
  const resolvedMcpUrl = (argFor("--mcp-url") ?? defaultMcpUrl()).replace(/\/+$/, "");
  const token = argFor("--token") ?? process.env.OMS_TOKEN;
  const spaceId = argFor("--space");
  const scope = argFor("--scope") ?? "secret";
  const vaultDir = argFor("--vault") ?? "./vault";
  const clients = parseClients(argFor("--client"));
  const ohmyselfRoot =
    argFor("--ohmyself-root") ?? (mode === "local" ? await findOhmyselfRoot(cwd) : undefined);

  const omsDir = path.join(cwd, ".oms");
  const configPath = path.join(omsDir, "config.yml");

  if ((await pathExists(configPath)) && !force) {
    console.error(`Already initialized (.oms/config.yml exists). Use --force to overwrite.`);
    process.exit(1);
  }

  const opts: InitOptions = {
    cwd,
    name,
    slug,
    mode,
    mcpUrl: resolvedMcpUrl,
    token,
    spaceId,
    scope,
    vaultDir,
    clients,
    force,
    ohmyselfRoot,
  };

  await ensureDir(omsDir);
  await ensureDir(path.join(omsDir, "mcp"));

  const results: string[] = [];

  results.push(
    `${await writeFileIfAllowed(configPath, buildConfigYaml(opts), force)} .oms/config.yml`,
  );
  results.push(
    `${await writeFileIfAllowed(path.join(omsDir, "README.md"), buildReadme(opts), force)} .oms/README.md`,
  );
  results.push(
    `${await writeFileIfAllowed(path.join(omsDir, ".gitignore"), "secrets.env\n*.local\n", force)} .oms/.gitignore`,
  );

  if (token) {
    results.push(
      `${await writeFileIfAllowed(path.join(omsDir, "secrets.env"), `OMS_TOKEN=${token}\n`, force)} .oms/secrets.env`,
    );
  } else if (mode === "hosted") {
    results.push(
      `${await writeFileIfAllowed(path.join(omsDir, "secrets.env.example"), "OMS_TOKEN=oms_your_token_here\n", force)} .oms/secrets.env.example`,
    );
  }

  const snippetOpts = {
    mode,
    mcpUrl: resolvedMcpUrl,
    token,
    spaceId,
    scope,
    vaultDir,
    ohmyselfRoot,
  };

  if (clients.includes("cursor")) {
    const cursorPath = path.join(cwd, ".cursor", "mcp.json");
    const status = await mergeJsonFile(cursorPath, cursorMcpConfig(snippetOpts), force);
    results.push(`${status} .cursor/mcp.json`);
  }

  if (clients.includes("claude")) {
    results.push(
      `${await writeFileIfAllowed(
        path.join(omsDir, "mcp", "claude-desktop.json"),
        `${JSON.stringify(claudeDesktopConfig(snippetOpts), null, 2)}\n`,
        force,
      )} .oms/mcp/claude-desktop.json`,
    );
  }

  if (clients.includes("codex")) {
    results.push(
      `${await writeFileIfAllowed(
        path.join(omsDir, "mcp", "codex.toml"),
        codexTomlFragment(opts),
        force,
      )} .oms/mcp/codex.toml`,
    );
  }

  if (mode === "local") {
    await ensureDir(path.isAbsolute(vaultDir) ? vaultDir : path.join(cwd, vaultDir));
    if (!ohmyselfRoot) {
      console.warn(
        "\nWarning: local mode but ohmyself monorepo not found. Install or pass --ohmyself-root for stdio MCP.",
      );
    }
  }

  console.log(`\noms init — ${name} (${mode})\n`);
  for (const r of results) console.log(`  ${r}`);

  console.log(`
Next:
  ${mode === "hosted" ? "• Create token at www.ohmyself.ai → Settings → MCP" : "• Add notes under " + vaultDir}
  • Reload Cursor (or paste .oms/mcp/claude-desktop.json into Claude config)
  • Ask the agent to run get_structure — contract 2.7

Docs: docs/OMS_INIT.md · .oms/README.md
`);
}
